### PR TITLE
Extract the generation of PDF to enable higher reusability

### PR DESCRIPTION
**Pull request by nbessi**

### CODE REVIEW

**Comment by yvaucher** [comment]
I guess this will close https://github.com/OCA/l10n-switzerland/issues/89 ?

**Comment by yvaucher** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by nbessi** [comment]
@yvaucher no it is not related to issue #89.

**Comment by nbessi** [comment]
Can somebody merge this one pelase

**Pull request merged**
