### PR TITLE
Add transifex to travis config plus update to match OCA template

### PR DESCRIPTION
**Pull request by yvaucher**
Follow template: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml

Add transifex: https://github.com/OCA/maintainer-quality-tools/issues/194

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by tafaRU** [comment]
LGTM :+1:

**Comment by yvaucher** [comment]
runbot was fixed in #142 this can be merged

**Comment by yvaucher** [comment]
I rebased on top of merged #142 to retrigger runbot build which should be green

**Comment by nbessi** [comment]
:+1:

**Pull request merged**
