### PR TITLE
get_bvr_ref refactoring

### PR DESCRIPTION
**Pull request by CSester**
Refactoring of the get_bvr_ref function to be more modular.

This is because we need to add other generation condition and strategy for LSV.

Initial MP is https://code.launchpad.net/~compassion/openerp-swiss-localization/lsv_prepare/+merge/229767

### CODE REVIEW

**Comment by nbessi** [comment]
Please can you merge with latest 7.0. It should fix travis build.

Regards

Nicolas

**Comment by CSester** [comment]
Ok, I merged with latest 7.0 changes. 

Regards

Cyril

**Comment by guewen** [comment]
:+1:

**Comment by nbessi** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
