### PR TITLE
Bugfixing in domain

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by guewen** [comment]
Could you explain this correction please? The comment above the lines (that was there already) does not help.

**Comment by nbessi** [comment]
Hello, 

Can you please attached an Issue to your patch explaining the problem.

Thanks

**Comment by ghost** [comment]
Hello, 

You can find the issue at https://github.com/OCA/l10n-switzerland/issues/106

Thanks

**Comment by nbessi** [comment]
@BT-csanchez thanks

**Comment by nbessi** [comment]
Seems Fine :+1: @vrenaville Can you review too please?

**Comment by bt-admin** [comment]
@vrenaville Can you please have a look into this? Thank you

**Comment by nbessi** [comment]
Seems @vrenaville is in holidays until next week

**Comment by bt-admin** [comment]
@nbessi Thanks for the information. Then we wait.

**Comment by nbessi** [comment]
@vrenaville ping ?

**Comment by vrenaville** [comment]
Hello, 

Sorry for the delay, it's okay for me :+1: 

Thanks for the fix

Vincent

**Comment by nbessi** [comment]
haa I merged too fast I was sure there was a third thumb up, I revert to respect OCA delay

**Comment by nbessi** [comment]
waiting for https://github.com/OCA/l10n-switzerland/pull/125 to be green

**Comment by nbessi** [comment]
I'm told it is OK can an OCA confirm?

**Comment by tafaRU** [comment]
Before to definetely merge I would suggest to modify or remove the comments above line 383 and line 406. Now they are not more appropriate.

Thank you in advance.

**Comment by ghost** [comment]
Should I update the branch removing the comments?

**Comment by tafaRU** [comment]
@BT-csanchez, yes or modifying them properly. Thanks!

**Comment by ghost** [comment]
@tafaRU  Ok I will modify it, and submit in this branch, 

Cheers!

**Pull request merged**
