### PR TITLE
[10.0] [BACKPORT] l10n_ch - swissqr report

### PR DESCRIPTION
**Pull request by yvaucher**
This backport the `l10n_ch` swissqr_report template and adapt it to
version 10.0

2020-06-22-165929_1778x936_scrot

### CODE REVIEW

**Comment by i-vyshnevska** [comment]
@yvaucher the build is failing

**Review by leemannd — CHANGES_REQUESTED** [review]
Functional testing:
- base works great
- error to be adressed: with long customer names in section _payable by_ the customer name is touching the border

**Comment by yvaucher** [comment]
@leemannd I'll merge this and we will go through other PRs to improve the module.

**Comment by yvaucher** [comment]
@leemannd finally I fixed the issue you mentionned in the current PR. But, we should have a pretty good working state here. So next one will be addressed in another PRs, I want to make this available as soon as possible.

**Pull request merged**
