### PR TITLE
12.0 add QRR pain001

### PR DESCRIPTION
**Pull request by davidwul**
Add the ability to include a QR invoice with QRR on a payement order and produce a pain001 expected (according to SIX implementation-guidelines-ct)

### CODE REVIEW

**Review by Martronic-SA — APPROVED** [review]
Tested and working as expected.
When the reference is ISR but the bank is QR iban we leave the CH01 local instrument and go to payment type 3.
Doc here [https://www.six-group.com/dam/download/banking-services/interbank-clearing/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf](url) on page 19.

**Comment by davidwul** [comment]
@Martronic-SA  thanks for the review and comment.
Indeed I used the six documentation, I hoped I did not forgot to add anything in regards to QRR.
at least, it has been test live successfully with a pain001 to the Raiffeisen Bank.

**Review by yvaucher — CHANGES_REQUESTED** [review]
@davidwul Thanks for the contrib.

Code looks good to me

Can you fix the 2 following lint issues?

l10n_ch_pain_base/models/account_move_line.py:6:1: E302 expected 2 blank lines, found 1
l10n_ch_pain_base/models/account_payment_line.py:12:89: E501 line too long (89 > 88 characters)

Plus could you squash the commits and give a proper commit message.

**Comment by davidwul** [comment]
lint issues should be fixed, 
@yvaucher I don't know if I did what you asked for regarding squashing commit,

**Comment by davidwul** [comment]
anything else can be done to push this forward?

**Comment by yvaucher** [comment]
@davidwul thanks for the changes, looks good to me.

**Review by yvaucher — APPROVED** [review]

**Pull request merged**
