### PR TITLE
return list of all banks if name is empty

### PR DESCRIPTION
**Pull request by BT-ojossen**
otherwise the customer thinks that there aren't any banks in the system.

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:  Agreed this is quite disturbing to see no bank unless you type some string to search for it.

**Comment by gurneyalex** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
Hi @BT-ojossen 

Thanks for the contribution, can you please have a look on the CI tools (travis and runbot need some love).

Regards,

Joël

**Comment by BT-ojossen** [comment]
Hi @jgrandguillaume 

We fixed the test_pylint problem. But we couldn't find out how to fix the flake8 problem coming from travis.

Also we couldn't fix the problem in runbot. It points to a problem with "report_xls". No idea how to fix this.

Regards,

**Comment by leemannd** [comment]
@BT-ojossen On this file you should add a blank line in the end and it's ok to me.

**Comment by BT-ojossen** [comment]
is fixed here, but not merged yet #220

**Comment by yvaucher** [comment]
#220 has been merged

**Pull request merged**
