### PR TITLE
add the possibility to validate every created voucher while importing…

### PR DESCRIPTION
**Pull request by eLBati**
… file

### CODE REVIEW

**Comment by nbessi** [comment]
:+1: but I realized that po file are missing. @eLBati it would be nice if you can add them in an other PR

**Comment by eLBati** [comment]
Thanks @nbessi here it is https://github.com/OCA/l10n-switzerland/pull/154

**Comment by nbessi** [comment]
Nice @eLBati

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
