### PR TITLE
[10.0][FIX] Postfinance statement attachments

### PR DESCRIPTION
**Pull request by ecino**
After update of Postfinance banking software, attachments in bank statements are no longer correctly parsed. This is fixing the parsing of the attachments.

### CODE REVIEW

**Comment by ecino** [comment]
Unfortunately the test files are with the old format... I will update them

**Comment by ecino** [comment]
Everything is fixed now.

**Review by yvaucher — APPROVED** [review]
I'll give my approval on good faith as you are the creator and maintainer of the module.

Would be great if you could create an other PR to link the technical documentation in the `postfinance_file_parser.py` file.
Do you have any documentation for the development to link?

**Comment by ecino** [comment]
@yvaucher Thanks! I will do that, I still have some work on refactoring code accross different modules. The new banking standards introduced a variety of formats with camt.052, camt.053 and camt.054 as well as pain.002 and pain.008. Some of that standards should be merged into bank-statement-import and some can be done here for Postfinance.

**Comment by yvaucher** [comment]
@ecino ok, thanks for the heads up.

**Comment by Highcooley** [comment]
I do get the following error while trying to import postfinance bank statements:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account_bank_statement_import/account_bank_statement_import.py", line 37, in import_file
    currency_code, account_number, stmts_vals = self.with_context(active_id=self.ids[0])._parse_file(base64.b64decode(self.data_file))
  File "/mnt/modules/open/account_bank_statement_import_camt/models/account_bank_statement_import.py", line 23, in _parse_file
    return parser.parse(data_file)
  File "/mnt/modules/open/l10n_ch_bank_statement_import_postfinance/models/postfinance_file_parser.py", line 52, in parse
    self.data_file)
  File "/mnt/modules/open/account_bank_statement_import_camt/models/parser.py", line 259, in parse
    statement = self.parse_statement(ns, node)
  File "/mnt/modules/open/l10n_ch_bank_statement_import_postfinance/models/postfinance_file_parser.py", line 71, in parse_statement
    result = super(XMLPFParser, self).parse_statement(ns, node)
  File "/mnt/modules/open/account_bank_statement_import_camt/models/parser.py", line 213, in parse_statement
    )[0]['date']
IndexError: list index out of range

Ist this problem related to this fix?

**Comment by ecino** [comment]
The error seems to come from module account_bank_statement_import_camt in[ OCA/bank-payment](https://github.com/OCA/bank-statement-import/tree/10.0). Please make sure you have the latest 10.0 version from this repository as it seems that the line 213 does not match the current state of repository.

**Comment by Highcooley** [comment]
@ecino tanks for your reply! Having updated to the latest version, I now do get:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account_bank_statement_import/account_bank_statement_import.py", line 37, in import_file
    currency_code, account_number, stmts_vals = self.with_context(active_id=self.ids[0])._parse_file(base64.b64decode(self.data_file))
  File "/mnt/modules/open/account_bank_statement_import_camt/models/account_bank_statement_import.py", line 23, in _parse_file
    return parser.parse(data_file)
  File "/mnt/modules/open/l10n_ch_bank_statement_import_postfinance/models/postfinance_file_parser.py", line 52, in parse
    self.data_file)
  File "/mnt/modules/open/account_bank_statement_import_camt/models/parser.py", line 259, in parse
  File "/mnt/modules/open/l10n_ch_bank_statement_import_postfinance/models/postfinance_file_parser.py", line 71, in parse_statement
    result = super(XMLPFParser, self).parse_statement(ns, node)
  File "/mnt/modules/open/account_bank_statement_import_camt/models/parser.py", line 213, in parse_statement
    if root_0_0 != 'GrpHdr':
IndexError: list index out of range

Still line 213 but of the newest parser.py. Any idea what could cause this issue?

**Comment by ecino** [comment]
The error doesn't seem related to this line of code. Did you restart the server and updated your modules? It's hard to troubleshoot at distance. Check your modules are all on **branch 10** and up to date.

**Comment by Highcooley** [comment]
After an update of all related modules, the CAMT file import now works. However, if a file only contains the current balance without any move lines, I get the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account_bank_statement_import/account_bank_statement_import.py", line 37, in import_file
    currency_code, account_number, stmts_vals = self.with_context(active_id=self.ids[0])._parse_file(base64.b64decode(self.data_file))
  File "/mnt/modules/open/account_bank_statement_import_camt/models/account_bank_statement_import.py", line 23, in _parse_file
    return parser.parse(data_file)
  File "/mnt/modules/open/l10n_ch_bank_statement_import_postfinance/models/postfinance_file_parser.py", line 52, in parse
    self.data_file)
  File "/mnt/modules/open/account_bank_statement_import_camt/models/parser.py", line 234, in parse
    statement = self.parse_statement(ns, node)
  File "/mnt/modules/open/l10n_ch_bank_statement_import_postfinance/models/postfinance_file_parser.py", line 71, in parse_statement
    result = super(XMLPFParser, self).parse_statement(ns, node)
  File "/mnt/modules/open/account_bank_statement_import_camt/models/parser.py", line 188, in parse_statement
    )[0]['date']
IndexError: list index out of range

**Comment by ecino** [comment]
Please check the buggy camt file, maybe replace sensitive data inside it (names and account numbers) and post it here so that we can see what's the problem.

**Comment by Highcooley** [comment]
The File seems to be legid, since it is similar to working files. Only the fact that there are no move lines seems to cause the problem. 

```
<?xml version="1.0" encoding="UTF-8"?>
<Document xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:camt.053.001.04 camt.053.001.04.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:iso:std:iso:20022:tech:xsd:camt.053.001.04">
<BkToCstmrStmt>
<GrpHdr>
<MsgId>20180508375204021426429</MsgId>
<CreDtTm>2018-05-09T01:46:19</CreDtTm>
<MsgPgntn>
<PgNb>1</PgNb>
<LastPgInd>true</LastPgInd>
</MsgPgntn>
<AddtlInf>Productive</AddtlInf>
</GrpHdr>
<Stmt>
<Id>20180508375204021426438</Id>
<ElctrncSeqNb>89</ElctrncSeqNb>
<CreDtTm>2018-05-09T01:46:19</CreDtTm>
<FrToDt>
<FrDtTm>2018-05-08T00:00:00</FrDtTm>
<ToDtTm>2018-05-08T23:59:59</ToDtTm>
</FrToDt>
<Acct>
<Id>
<IBAN>CHsomething</IBAN>
</Id>
<Ownr>
<Nm>Company Name</Nm>
</Ownr>
</Acct>
<Bal>
<Tp>
<CdOrPrtry>
<Cd>OPBD</Cd>
</CdOrPrtry>
</Tp>
<Amt Ccy="CHF">1000.00</Amt>
<CdtDbtInd>CRDT</CdtDbtInd>
<Dt>
<Dt>2018-05-08</Dt>
</Dt>
</Bal>
<Bal>
<Tp>
<CdOrPrtry>
<Cd>CLBD</Cd>
</CdOrPrtry>
</Tp>
<Amt Ccy="CHF">1000.00</Amt>
<CdtDbtInd>CRDT</CdtDbtInd>
<Dt>
<Dt>2018-05-08</Dt>
</Dt>
</Bal>
</Stmt>
</BkToCstmrStmt>
</Document>
```

**Comment by davidwul** [comment]
Hi, 
yes, it failed if there are no move inside the camt.
It won't failed if you import through the FDS. (this case is taken into account)
But it will if you import it directly.
Try with a camt with moves inside.

**Comment by ecino** [comment]
@Highcooley You could open an issue on repo OCA/bank-statement-import, because it's the module camt import that is failing at importing empty bank statements. Your issues are not related to postfinance files, especially not with this pull request.

**Comment by Highcooley** [comment]
All right, thank you very much for your support. I‘ll check if I can do FDS or check with the bank-statement-import repo.

**Pull request merged**
