### PR TITLE
Rename BVR and BVR/ESR to ISR in english and make it the base term

### PR DESCRIPTION
**Pull request by yvaucher**
Renaming and migration script for `l10n_ch_base_bank` module

### CODE REVIEW

**Comment by davidwul** [comment]
:+1: 
Make sense. Why not rename also CCP ( french for Compte de Chèque Postaux) by CP (Compte Postal) in French and PC (Postkonto) in german... but no idea in english ... I would put PC

**Comment by yvaucher** [comment]
That's a good idea, I didn't check what it would require to change CCP.

On the other hand I find CCP more accurate than CP and PC abreviations can be ton of things.
But I'm biased as my mother tongue is french.

By the way isn't it PC-Konto or CP-Konto instead of just PC ?
In the de.po files we currently have CP-Konto but that could be wrong.

I could put postal number/account in english to be translated by CCP and PC-Konto

**Comment by yvaucher** [comment]
Seems the CP-Konto in translations is a mistake

**Comment by davidwul** [comment]
Yes PC-Konto is clearer than just PC.
And for me postal account is good in english.

**Comment by yvaucher** [comment]
I'll merge this renaming as stand alone, renaming CCP deserve an other PR

**Pull request merged**
