### PR TITLE
[16.0][MIG] l10n_ch_account_tags: Migration to 16.0

### PR DESCRIPTION
**Pull request by simoneversienti**

### CODE REVIEW

**Comment by simoneversienti** [comment]
Sorry, i'm fixing it.

**Review by yvaucher — APPROVED** [review]

**Comment by simoneversienti** [comment]
@yvaucher there's an error. This is the migration of `l10n_ch_account_tags` and not of `l10n_account_tags`. My mistake in PR title. I update it now

**Pull request merged**
