### PR TITLE
[9.0][MIG] fds_upload_dd + migration scrips lsv_dd

### PR DESCRIPTION
**Pull request by ecino**
Since #305 is stale since March, I took the initiative to take the PR further and include fds_upload_dd module in the migration.

I also added migration scripts for module `lsv_dd` so that migration from v8 is taken into account.

See #305 for other modifications.

Everything is tested since long time and working well.

### CODE REVIEW

**Comment by BT-astauder** [comment]
Hello @ecino There is another small patch in the original branch:
https://github.com/OCA/l10n-switzerland/pull/305/commits/f2077123ea750f4d7813ac66b7ef58d8b3e0bff7

Would you integrate this also here?

**Comment by ecino** [comment]
@BT-astauder cherry-picked the commit

**Comment by ecino** [comment]
@yvaucher @guewen Willing to review?

**Comment by yvaucher** [comment]
@ecino I merged #305, willing to rebase on it ?

**Comment by ecino** [comment]
rebased

**Comment by yvaucher** [comment]
Travis errors where already there, I'm merging.

**Review by yvaucher — APPROVED** [review]

**Pull request merged**
