### PR TITLE
9.0 port l10n ch fds postfinance

### PR DESCRIPTION
**Pull request by philhug**
work in progress for the FDS port

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi,

Thanks for the contributions. Can you check the Travis errors please ?

Regards,

Joël

**Comment by yvaucher** [comment]
README.rst files are missing to describe the modules.

Please find the template here: https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

**Comment by hug-abacus** [comment]
@ecino I merged in your changes and will now fix the 9.0 port.

**Comment by philhug** [comment]
@ecino I merged in your changes and will now fix the 9.0 port.

**Comment by ecino** [comment]
@philhug great, thanks!

**Comment by yvaucher** [comment]
Hello,

Still few pep8 issues to fix:

```
l10n_ch_fds_postfinance/models/fds_authentication_keys.py:31:80: E501 line too long (121 > 79 characters)
l10n_ch_fds_postfinance/models/fds_authentication_keys.py:33:1: E302 expected 2 blank lines, found 1
l10n_ch_fds_postfinance/models/fds_postfinance_account.py:33:80: E501 line too long (122 > 79 characters)
```

Does this module still depends on l10n_ch_sepa ? shouldn't it depends on `l10n_ch_pain_credit_transfer` instead ?

**Comment by ecino** [comment]
@yvaucher Fixed the issues, added fds_sepa module migration and some tests in #323

**Comment by yvaucher** [comment]
@ecino thanks then I close this PR in favor of yours

superseeded by #323

**Pull request closed without merging**
