### PR TITLE
[10.0] Add new module: "Switzerland - Payroll Reports"

### PR DESCRIPTION
**Pull request by jcoux**
Switzerland - Payroll Reports
=============================

This module extends the functionality of payroll to:

* Customize the Pay Slip report
* Add a Pay Slip Yearly report

These 2 reports follow the Swissdec guidelines (p.84 and p.87) (Sorry PDF is in french):
https://www.swissdec.ch/fileadmin/user_upload/Software-Hersteller/RL4.0/RichtlinienLohndatenverarbeitung20130514_20130519_f.pdf

This PR depends of : https://github.com/OCA/l10n-switzerland/pull/315

### CODE REVIEW

**Comment by damdam-s** [comment]
:+1: technical review

**Comment by open-net-sarl** [comment]
After a quick review i noticed you put the noupdate flag on rules. We don't want that.
We did few modifications on hr_payroll v10 to avoid having to put this flag on rules.

So please remove this flag from the xml. Thanks.

**Comment by open-net-sarl** [comment]
- We updated ch_hr_payroll and added one new rule and one new category to keep the information of the total deductions, you should count with that one in the payslip report (if it is in the slary structure).

- I also noticed that in the payslip pdf report some columns should be aligned to the right, "Amount", "Rate" and "Total", also, the column "Name" should have the description of the rule (if it exists).

**Comment by jcoux** [comment]
@open-net-sarl Thanks for your review. I will look them next week.

**Comment by damdam-s** [comment]
:+1: ￼ technical review

**Comment by jcoux** [comment]
@open-net-sarl I fixed report and data after your review.
And I added a filter to not display payslip line with a zero total in payslip report.

**Comment by yvaucher** [comment]
@jcoux still WIP ?

**Comment by jcoux** [comment]
@yvaucher Yes and not, I have finished developments, but i only waiting the merge of the PR in dependency.

**Comment by open-net-sarl** [comment]
in the file: **_report_payslip.xml_**

line with the rules order: 
`<t t-foreach="o.line_ids.filtered(lambda line: line.appears_on_payslip and line.total).sorted(key=lambda line: `**line.code**`)" t-as="line">`

should be changed to be ordered by **sequence**
@jcoux @yvaucher

**Review by didierdonze — APPROVED** [review]
Ok, from a business perspective. Can it be merged?

**Review by didierdonze — CHANGES_REQUESTED** [review]
Sorry, wrong PR. We will implement @open-net-sarl comments.

**Comment by jcoux** [comment]
@didierdonze @open-net-sarl 
I have rebased after the merge of https://github.com/OCA/l10n-switzerland/pull/315 and I have add 2 commits (one for the asked fix, and one for fix the rebase)

**Review by yvaucher — APPROVED** [review]

**Pull request merged**
