### PR TITLE
Fixed inheritance

### PR DESCRIPTION
**Pull request by stephanamann**
See Issue #217

### CODE REVIEW

**Comment by yvaucher** [comment]
Thanks, you probably also want to enable this module in this PR:

https://github.com/OCA/l10n-switzerland/blob/8.0/l10n_ch_payment_slip_account_statement_base_completion/__openerp__.py#L52

**Comment by stephanamann** [comment]
## We’re not using this module, so I can’t say anything about it ...

Dr. Stephan Amann

Glue Software Engineering AG | Schwarztorstrasse 31 | 3007 Bern
O +41 31 385 30 11 | F +41 31 385 30 18 | D +41 31 385 30 33
M +41 79 441 62 39 | stephan.amann@glue.ch mailto:stephan.amann@glue.ch | www.glue.ch http://www.glue.ch/

**Comment by yvaucher** [comment]
Thus I misunderstood your last message: https://github.com/OCA/l10n-switzerland/issues/217#issuecomment-261036546

Aren't you using  l10n_ch_payment_slip_account_statement_base_completion module ?
You meant that you extracted the wizard somehow in another module ?

**Comment by stephanamann** [comment]
We are using the following l10n modules:
glue_l10n_ch_payment_slip (extension of l10n_ch_payment_slip)
Camptocamp - Modules:
l10n_ch
l10n_ch_bank
l10n_ch_base_bank
l10n_ch_dta
l10n_ch_dta_base_transaction_id
l10n_ch_payment_slip
l10n_ch_payment_slip_base_transaction_id
l10n_ch_states
l10n_ch_zip
l10n_multilang

However, for the time being we only process BESR Files manually downloaded from UBS/Postfinance. We currently make no Payments (DTA) from odoo.

## Hope, this clarifies it.

Dr. Stephan Amann

Glue Software Engineering AG | Schwarztorstrasse 31 | 3007 Bern
O +41 31 385 30 11 | F +41 31 385 30 18 | D +41 31 385 30 33
M +41 79 441 62 39 | stephan.amann@glue.ch mailto:stephan.amann@glue.ch | www.glue.ch http://www.glue.ch/

**Comment by yvaucher** [comment]
Ok thus I'll merge that change as it.

**Pull request merged**
