### PR TITLE
[11.0][MIG] l10n_ch_bank_statement_import_postfinance

### PR DESCRIPTION
**Pull request by eicher31**
Migrate from 10.0 and update to 11.0

Depends on:

- [x] OCA/bank-statement-import#218

### CODE REVIEW

**Comment by eicher31** [comment]
Depends of https://github.com/OCA/bank-statement-import/pull/218

**Review by ecino — APPROVED** [review]
I fixed some issues with the Javascript, tested and everything looks fine for me. The tests will fail until the PR on bank-statement-import will be merged, because the CAMT parser is erasing the statement line names with some transaction numbers.

**Comment by ecino** [comment]
@yvaucher this is ready to be merged I think. Don't know what the runbot build issue is however? I tested it on my side and it works fine.

**Comment by yvaucher** [comment]
@ecino runbot is read due to some warning, this is not blocking -> merging right now.

Thanks

**Pull request merged**
