### PR TITLE
[10.0][MIG] l10n_ch_payment_slip

### PR DESCRIPTION
**Pull request by grindtildeath**
Migration done.

Depends on :
- [x] ~~https://github.com/OCA/bank-statement-reconcile/pull/165~~
- [x] https://github.com/OCA/bank-statement-reconcile/pull/164

### CODE REVIEW

**Review by leemannd — APPROVED** [review]
Only code review

**Comment by yvaucher** [comment]
Updated dependency

**Comment by ghost** [comment]
Hi guys, what's the state of this PR? Is there still work to do? Otherwise, I suggest you merge it.

**Comment by yvaucher** [comment]
@BT-faebi We can't merge it before https://github.com/OCA/bank-statement-reconcile/pull/164

**Comment by yvaucher** [comment]
Amended the last commit to relaunch travis

**Comment by yvaucher** [comment]
@grindtildeath could you cherry pick those 2 commits from 9.0:

https://github.com/OCA/l10n-switzerland/commit/d00e34977f72a7030c556fdbc9619a560ab307c3#diff-cc4d9504bebc2e47a10b0d46d145cf72
https://github.com/OCA/l10n-switzerland/commit/58b1367c48200355922b87e41a39318645cb7cc7#diff-cc4d9504bebc2e47a10b0d46d145cf72

**Pull request merged**
