### PR TITLE
[11.0] l10n_ch_pain_credit_transfer: Update broken link

### PR DESCRIPTION
**Pull request by SimoRubi**
The existing link is broken, I think the new link should be of the pointed out specifications; can someone have a look?
Thanks!

### CODE REVIEW

**Comment by yvaucher** [comment]
I'm not in favor for a Credit Suisse link. Six interbanking is the source reference.

**Comment by SimoRubi** [comment]
> I'm not in favor for a Credit Suisse link. Six interbanking is the source reference.

Thanks for having a look!
Existing link is broken: 
image
Do you a working link to the guidelines then?

**Comment by yvaucher** [comment]
Seems they have renamed the path.

I can find back some files here:
https://www.six-group.com/en/services/search.html?as_q=implementation_guidelines_ct.pdf&division=all

The latest I can find is v1.9:
https://www.six-group.com/dam/download/banking-services/interbank-clearing/en/standardization/iso/swiss-recommendations/archives/implementation-guidelines-ct/implementation-guidelines-ct_v1_9.pdf

The one from SIX interbanking has 72 pages, whereas the one from Credit suisse has 41 pages.

Seems the one from CS is quite incomplete.

**Comment by yvaucher** [comment]
BTW I realize the broken link is pointing to the FR version.

This (same as in previeus comment) will be the EN version which is better: https://www.six-group.com/dam/download/banking-services/interbank-clearing/en/standardization/iso/swiss-recommendations/archives/implementation-guidelines-ct/implementation-guidelines-ct_v1_9.pdf

**Comment by SimoRubi** [comment]
Thanks @yvaucher I updated the link, is this ok now?

**Review by yvaucher — APPROVED** [review]

**Pull request merged**
