### PR TITLE
Set to paid expenses linked to confirmed payslip

### PR DESCRIPTION
**Pull request by open-net-sarl**
The state of the expense is set to 'paid' if the linked payslip is set to confirmed.

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi,

Thanks for the contribs ! Can you check Travis error please ?

Regards,

Joël

**Comment by dcoopennet** [comment]
@jgrandguillaume 
I checked travis, but the issue came from another module (l10n_ch_sepa/base_sepa/pain_001.py).
Would you like me to create another PR on this module to check the travis issues ?

**Comment by leemannd** [comment]
@dcoopennet Hello, Just add a blank line in the end of the file and your commit will be clean

**Comment by open-net-sarl** [comment]
@leemannd I think i alread fix the blank line in previous commit named "Fix PEP8". There is only one file that was modified.

**Comment by leemannd** [comment]
:+1:

**Comment by dcoopennet** [comment]
@leemannd @jgrandguillaume Is there anything to fix on the PR ? If not please merge it.

**Comment by dcoopennet** [comment]
@leemannd @jgrandguillaume 
The following PR fails because of this:
======== Testing test_flake8 ========
l10n_ch_sepa/base_sepa/pain_001.py:92:17: W503 line break before binary operator
l10n_ch_sepa/base_sepa/pain_001.py:112:21: W503 line break before binary operator

+=======================================
|  Tests summary:
|---------------------------------------
| test_flake8                 FAIL
| test_pylint                 Success
+=======================================
So please don't consider this. This commit doesn't change anything in l10n_ch_sepa.
And if everything is OK, please merge it.

**Comment by yvaucher** [comment]
Please rebase it on 8.0, CI tests have been fixed

**Comment by yvaucher** [comment]
@open-net-sarl We usually do a rebase instead of a merge to have cleaner history.

With for exemple: `git rebase -i origin/8.0`

**Pull request closed without merging**
