### PR TITLE
[14.0][MIG] l10n_ch_pain_base : Migration to 14.0

### PR DESCRIPTION
**Pull request by ecino**
Take another attempt to migrate the module, as previous PR are stale. (#668)

### CODE REVIEW

**Comment by ecino** [comment]
Travis errors are not related the migrated module :no_good:

**Comment by ecino** [comment]
@OCA/local-switzerland-maintainers @TDu Is there anyone available to review this pull request, or do you know who the current maintainers of the l10n-switzerland repository are? It's concerning to see the repository inactive, and I'd like to help ensure its continued development. I'm willing to contribute and take on a role as a maintainer if that's a possibility. Please let me know how I can assist in reviving this project.

**Comment by TDu** [comment]
Not familiar with this module. I just restarted the tests on Travis to see... As the 14 branch is green now.
It is a shame this module never had tests.
The last commit could be squashed into the previous migration commit.

**Comment by ecino** [comment]
Squashed the commits as requested.

**Comment by ecino** [comment]
@TDu Please let me know how we can move forward with this. Many other modules depend on it and we could greatly extend the functionalities of the swiss-localization repository if we take some time to review the pending pull requests.

**Comment by ecino** [comment]
@TDu This module is not useful on its own, it's more a technical basis for the two sub-modules, so it's hard to make tests for it, especially because it doesn't add the pain flavors in the payment methods. Do you think we should move this out of the submodules in order to make this module testable, or what would be the approach?

@alexis-via @leemannd Can you review please?

**Review by TDu — APPROVED** [review]

**Pull request merged**
