### PR TITLE
[9.0][MIG] l10n_ch_lsv_dd

### PR DESCRIPTION
**Pull request by BT-astauder**
Supports new and only the version 3.0 for the DD-CH of postfinance
Extended support for special characters in LSV (according to ZKB, Zürcher Kantonalbank)

### CODE REVIEW

**Comment by BT-astauder** [comment]
This is WIP

**Comment by ecino** [comment]
Any news about this? I tested the modules and it seems to work well.

**Comment by BT-astauder** [comment]
We tested this for Postfinance and ZKB and both institutions accepted it. So WIP can be removed and merged when nothing else blocks it.

**Comment by ecino** [comment]
👍

**Comment by ecino** [comment]
Can we merge this one?

**Review by ecino — CHANGES_REQUESTED** [review]
Migration from v8.0 doesn't work because of data changes. Please include this commit that would add migration scripts and prevent such failure : https://github.com/CompassionCH/l10n-switzerland/commit/930d83fb311aa511c3ae9c4c243313c437c33a84

**Comment by yvaucher** [comment]
@BT-astauder thanks for the migration, merging it now

**Pull request merged**
