### PR TITLE
[MIG] server_env_ebill_paynet: Migration to 14.0

### PR DESCRIPTION
**Pull request by dzungtran89**
Dependencies:
- ebill_paynet: https://github.com/OCA/l10n-switzerland/pull/595

Notes:
- This module is migrated from this [commit](https://github.com/camptocamp/l10n-switzerland/tree/4110de201285192e67780467d95dcfc57230ccb2/server_env_ebill_paynet)

### CODE REVIEW

**Comment by mmequignon** [comment]
I think we are losing the git history here.

**Comment by dzungtran89** [comment]
thx @mmequignon , I'll update it

**Review by mmequignon — APPROVED** [review]

**Comment by hailangvn** [comment]
We will fix the travis.

**Comment by hailangvn** [comment]
The travis is green now.

**Comment by TDu** [comment]
Looks like you lost some information on the migration https://github.com/OCA/l10n-switzerland/blob/13.0/server_env_ebill_paynet/readme/CONTRIBUTORS.rst

**Comment by dzungtran89** [comment]
I had thought that I would update it in this https://github.com/OCA/l10n-switzerland/pull/596, is it okay to you?

**Comment by dzungtran89** [comment]
Hi @TDu , the PR has been updated, it's synced with your readme fix in the PR https://github.com/OCA/l10n-switzerland/pull/623

**Review by leemannd — APPROVED** [review]

**Review by TDu — APPROVED** [review]
@dzungtran89 Thanks for fixing it

**Comment by TDu** [comment]
@dzungtran89 all dependencies have been merged. You can update `test-requirements.txt`

**Comment by dzungtran89** [comment]
Hi @TDu , the PR has been updated

**Review by sebalix — APPROVED** [review]

**Pull request merged**
