### PR TITLE
[14.0][MIG] l10n_ch_pain_direct_debit : Migration to 14.0

### PR DESCRIPTION
**Pull request by ecino**
Depends on [l10n_ch_pain_base](#702 ).

### CODE REVIEW

**Comment by ecino** [comment]
Still waiting for pain_base module to be available.

**Comment by ecino** [comment]
Last bit of the pain modules for Switzerland. After this being merged, I will probably migrate them in the newer versions and put them as a single pull request. @alexis-via Would you like reviewing this one? I think it was never implemented completely at the time the module was published, but this version should be working.

@yvaucher I wanted to add the "Postfinance Bank Account" in the demo data of the `l10n_ch_base_bank` module, for using it in the tests. But by doing so, the tests of the modules did break and I had to change a few things, but I'm not completely sure if all changes are ok. Would you like to check the changes in this module?

**Comment by ecino** [comment]
@alexis-via @TDu @yvaucher can someone review this one?

**Comment by TDu** [comment]
@ecino Hello, could you fix the pre-commit error and rebase if needed ? Thank you

**Comment by davidwul** [comment]
@TDu 
rebased and pre-commit fixed

**Pull request closed without merging**
