### PR TITLE
Missing account_payment dependence

### PR DESCRIPTION
**Pull request by paulius-sladkevicius**

### CODE REVIEW

**Comment by eLBati** [comment]
:+1:

**Comment by guewen** [comment]
What is the thing that depends on this module in `l10n_ch_payment_slip`?

**Comment by guewen** [comment]
I found it: https://github.com/OCA/ocb/blob/8.0/addons/account_payment/account_move_line.py#L76

:+1:

**Comment by guewen** [comment]
Thanks

**Comment by eLBati** [comment]
I found reference to `payment.line` here
https://github.com/komsas/l10n-switzerland/blob/ef08ac06aded68676271cd5ef7f40268dabf8003/l10n_ch_payment_slip/payment.py#L25

**Pull request merged**
