### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jmvandel**
Small cosmetic changes

### CODE REVIEW

**Comment by jmvandel** [comment]
I signed the CLA long time ago.

**Comment by jgrandguillaume** [comment]
Hi Jean-Marc,

I agree you did, I just check that. The trouble comes from the fact you never communicated your Github Login (so we can't match you).

I've corrected this issue now and it should be alright. Thanks for contributing here.

Regards,

Joël

**Comment by jgrandguillaume** [comment]
I've review your proposal, I'm :+1:

**Comment by open-net-sarl** [comment]
Salut Joël ! 

Il y a bien longtemps que je ne code plus, je n'avais donc pas pris de compte Github ... 
Mais bon, l'important c'est de participer ! :-) 

Avec mes plus sincères salutations, 

Jean-Marc Vandel 
CTO - Ing. info. dipl. EPFL 

Open Net Sàrl 
Rue de l'Industrie 59 
CH-1030 Bussigny 

www.open-net.ch 
+41 79 212.65.94 
jmv@open-net.ch

**Comment by leemannd** [comment]
Thank you! :+1:

**Pull request merged**
