### PR TITLE
Correct wrong property in the payment_term

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nbessi** [comment]
Fix seems correct it just breaks pep8

**Comment by BT-astauder** [comment]
So can this be merged? I guess pep8 should not be corrected.

**Comment by nbessi** [comment]
@BT-astauder @BT-csanchez  can you please merge https://github.com/BT-csanchez/l10n-switzerland/pull/2 it should fix PEP8

**Comment by yvaucher** [comment]
@BT-astauder @BT-csanchez PEP8 is part of the standard set by OCA. It needs to be corrected.

**Comment by bt-admin** [comment]
Thank you @nbessi . Ok new code has to follow PEP8.

**Comment by nbessi** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by yvaucher** [comment]
@BT-csanchez BTW your local git config is missing email adress. Github needs it to link it to you github account.
See https://github.com/BT-csanchez/l10n-switzerland/commit/e528e38aec6f5bbeb32dbacc761a37199172e5d6

**Pull request merged**
