### PR TITLE
[14.0][ADD] Payroll e-certificate for Switzerland

### PR DESCRIPTION
**Pull request by ecino**
This module extends the functionality of hr and payroll to allow you to extract payroll of the employees to import them in the swiss certificate platform <https://www.elohnausweis-ssk.ch/fr/#/>

### CODE REVIEW

**Comment by ecino** [comment]
Tests failing may be fixed with #700

**Comment by ecino** [comment]
@OCA/local-switzerland-maintainers Review is needed, thanks.

**Comment by jguenat** [comment]
This looks interesting, I might need it soon, have to find the time to review it.

**Comment by ecino** [comment]
Green lights, missing a review and I will merge.

**Pull request closed without merging**
