### PR TITLE
[14.0][ADD] module l10n_ch_adr_report

### PR DESCRIPTION
**Pull request by sonhd91**
Depends on the PR [[14.0][MIG] l10n_eu_product_adr #109](https://github.com/OCA/community-data-files/pull/109)
Porting PR [[13.0][ADD] adr product hook to filter move for report](https://github.com/OCA/community-data-files/pull/114/)

### CODE REVIEW

**Review by sebalix — COMMENTED** [review]
We could drop the `[14.0]` term from the commit message (commits should not refer to a particular version, excepting migration ones).

**Comment by sonhd91** [comment]
> We could drop the `[14.0]` term from the commit message (commits should not refer to a particular version, excepting migration ones).

commit message updated, thanks

**Comment by TDu** [comment]
Knowing that the depending module https://github.com/OCA/community-data-files/pull/109 has had a lot of changes when migrated to 14.0, I would think this will need some too.

**Comment by sonhd91** [comment]
> Knowing that the depending module [OCA/community-data-files#109](https://github.com/OCA/community-data-files/pull/109) has had a lot of changes when migrated to 14.0, I would think this will need some too.

Nothing change since I depended on PR#109 so no need to sync anymore, btw I will keep tracking change on PR#109 from now on,  thanks

**Review by sebalix — APPROVED** [review]
@sonhd91 can you remove the `[13.0]` part of `[13.0][ADD] adr product hook to filter move for report` commit message?
Otherwise LG

**Review by leemannd — APPROVED** [review]

**Pull request closed without merging**
