### PR TITLE
[13.0][MIG] l10n_ch_base_bank - reduced

### PR DESCRIPTION
**Pull request by yvaucher**
Superseed of #516 

This depends on the following patches on Odoo core:

- [x] https://github.com/odoo/odoo/pull/51544
- [x] https://github.com/odoo/odoo/pull/51560
- [x] https://github.com/odoo/odoo/pull/51634
- [x] https://github.com/odoo/odoo/pull/51635
- [ ] ~https://github.com/odoo/odoo/pull/51637~

This is a slim version of the module `l10n_ch_base_bank`, as some features and fixes have their place in Odoo.

### CODE REVIEW

**Review by TDu — APPROVED** [review]

**Comment by gurneyalex** [comment]
@yvaucher what is the status of this PR? the last PR on Odoo  is closed, and you say it's ok, but #578  is red -> how can we move on here?

**Comment by yvaucher** [comment]
@gurneyalex AFAIK this module has been used since a while on our projects in v13

**Comment by TDu** [comment]
Yes thank you. Go :robot:

**Comment by TDu** [comment]
@yvaucher Looks like the merge failed because of duplicate in the .po file https://travis-ci.com/github/OCA/l10n-switzerland/jobs/456034459#L914
Would be great if you could fix and try merging again, thanks.

**Comment by yvaucher** [comment]
@TDu thanks for the pointer

**Pull request merged**
