### PR TITLE
[PORT] Change installable to True

### PR DESCRIPTION
**Pull request by open-net-sarl**
No changes, just tested everything seems good.
Module base_location PR : https://github.com/OCA/partner-contact/pull/355

### CODE REVIEW

**Comment by yvaucher** [comment]
Please also change version in the manifest

**Comment by open-net-sarl** [comment]
@yvaucher Version changed for both modules

**Comment by leemannd** [comment]
@open-net-sarl In your last commit you deleted the csv file with the data.

**Review by yvaucher — CHANGES_REQUESTED** [review]
Well don't delete the csv file.

Please amend your last commit to fix that. We don't want to overload git history with that kind of change.

**Comment by open-net-sarl** [comment]
@yvaucher Done

**Review by yvaucher — APPROVED** [review]

**Comment by yvaucher** [comment]
Thanks, Waiting on base_location to be merged

**Comment by leemannd** [comment]
@open-net-sarl Thank you for the port. Just one friendly reminder. When porting a module, too many people forget to ping it in the issues => https://github.com/OCA/l10n-switzerland/issues/271 . It improves greatly the cooperation. :)

**Comment by leemannd** [comment]
@open-net-sarl Can you also change in the two readme files the version triggered for runbot?

**Comment by yvaucher** [comment]
Closing the history is unclean and some changes in xml file and python files are missing, I'll make a PR per module soon.

**Comment by yvaucher** [comment]
superseeded by #292 and #293

**Pull request closed without merging**
