### PR TITLE
[FIX][7.0] Allow manual payment creation without invoice

### PR DESCRIPTION
**Pull request by leemannd**
The actual implementation was taking informations from invoice.
This PR aims to take these informations where they are setted, even if you have no invoice.

### CODE REVIEW

**Comment by leemannd** [comment]
@yvaucher @vrenaville Do you have the time for a review?

**Review by vrenaville — APPROVED** [review]
LGTM, please check why Travais failed
+1

**Comment by leemannd** [comment]
@vrenaville Travis is broken since ages on the V `7.0`.
EDIT: it fails since 2015.

**Review by Tonow-c2c — APPROVED** [review]
LGTM but can be trying to repair flake8 ?

**Review by p-tombez — APPROVED** [review]

**Review by yvaucher — APPROVED** [review]
LGTM, could you solve those 2 lint errors though ?

```
************* Module l10n_ch_sepa.__openerp__
l10n_ch_sepa/__openerp__.py:22: [C8102(manifest-required-key), ] Missing required key "license" in manifest file
l10n_ch_sepa/__openerp__.py:22: [C8106(manifest-version-format), ] Wrong Version Format "1.1" in manifest file. Regex to match: "(4\.2|5\.0|6\.0|6\.1|7\.0|8\.0|9\.0|10\.0|11\.0|12\.0)\.\d+\.\d+\.\d+$"
```

**Comment by yvaucher** [comment]
I'll do the change myself after merge

**Pull request merged**
