### PR TITLE
Payslip-based journal entries now inherits correctly of the partner's name

### PR DESCRIPTION
**Pull request by open-net-sarl**
This modification has been done to compensate a problem inherent to Many2one fields that related to a One2many field: the value is taken from the first record encountered.
In the case of journal items, more often than not, the first record doesn't has the link to the partner's name, which leads to a journal item without a partner defined.
The modification catches the partner's name by detecting the journal item linked to a payable account..

### CODE REVIEW

**Comment by open-net-sarl** [comment]
@yvaucher can you help us with what the oca-clabot is asking for? cyp-opennet is one of the users of Open Net, which signed an entity cla as an organization, and cyp is one of the contacts, as is jae.

**Comment by open-net-sarl** [comment]
@yvaucher Thanks for your advice

**Comment by yvaucher** [comment]
Few lint check to fix https://travis-ci.org/OCA/l10n-switzerland/jobs/89262025

**Comment by open-net-sarl** [comment]
@yvaucher 
Thanks to remove the 'Needs fixing' and prepare for commit, time for november salary is coming..

**Comment by yvaucher** [comment]
@open-net-sarl When you do some new commits, feel free to add a comment to ping the followers. Only changing commits won't warn about the changes.

:+1:

**Comment by open-net-sarl** [comment]
@yvaucher 

Ok, wil know it

**Comment by open-net-sarl** [comment]
@yvaucher Hi, how could we find someone for the review ? The changes were small, just copying the partner id in the account.move

**Comment by yvaucher** [comment]
@open-net-sarl You can make a review for a college, I see that commits are from @cyp-opennet  (Yvon-Philippe)

Who is under the main github account account ? Just give a :+1: and I'll merge it and perhaps sign to show it's not the same person as the commiter ? So we would comply with the OCA rules of 2 reviews after 5 days or more.

**Comment by cyp-opennet** [comment]
:+1:

**Comment by yvaucher** [comment]
Ok, thanks I'll merge this.

Sorry to be that strict with OCA rules. Also, this way I'm sure you know that you can do a code / functional review even for your colleagues to speed the process especially as opennet is the author of the module. Otherwise I'm usually stuck with my single review and waiting.

**Comment by open-net-sarl** [comment]
Hello, 

Yes, I see that we have more contributors than reviewer. 

Difficult to solve this issue. 

Cordiales salutations 

Eberhard J-A 
CEO & Founder 
Certified Odoo Functional Specialist 

Open Net Sàrl 
www.open-net.ch 
59, Rue de l'industrie 
1030 Bussigny 
T: +41 (21) 701 42 45 
Autoroute A1, Sortie "Crissier / Bussigny" 
Bus TL 17, arrêt Croix-de-Plan 

----- Mail original -----

**Pull request merged**
