### PR TITLE
[ADD] missing customer address above scan line

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by nbessi** [comment]
Right you are.  Please use 745 for x coordinate in order to align with ref line

**Comment by eLBati** [comment]
@nbessi done

**Comment by nbessi** [comment]
Waiting for  #99

**Comment by nbessi** [comment]
Ahh green :smile:

**Comment by nbessi** [comment]
@yvaucher a small review please

**Comment by yvaucher** [comment]
:+1:

**Comment by nbessi** [comment]
:+1:

**Comment by tafaRU** [comment]
:+1:

**Pull request merged**
