### PR TITLE
[8.0][ADD] l10n_ch_dta ported to the new api

### PR DESCRIPTION
**Pull request by tafaRU**
This PR depends on https://github.com/OCA/l10n-switzerland/pull/56

### CODE REVIEW

**Comment by nbessi** [comment]
Please rebase on https://github.com/OCA/l10n-switzerland/pull/56

**Comment by nbessi** [comment]
It might also be clever to fix error reveald by that PR

**Comment by tafaRU** [comment]
@nbessi just rebased on https://github.com/OCA/l10n-switzerland/pull/56

**Comment by tafaRU** [comment]
As reminder, **_test_pylint**_ failed due to:

```
l10n_ch_dta/wizard/unicode2ascii.py:26: [W0109(duplicate-key), ] Duplicate key u'\xd8' in dictionary
l10n_ch_dta/wizard/unicode2ascii.py:26: [W0109(duplicate-key), ] Duplicate key u'\xf8' in dictionary
l10n_ch_dta/wizard/unicode2ascii.py:26: [W0109(duplicate-key), ] Duplicate key u'\u0141' in dictionary
l10n_ch_dta/wizard/unicode2ascii.py:26: [W0109(duplicate-key), ] Duplicate key u'\u0142' in dictionary
l10n_ch_dta/wizard/unicode2ascii.py:558: [W0621(redefined-outer-name), coroutine.start] Redefining name 'argz' from outer scope (line 619)
```

**Comment by tafaRU** [comment]
Now PR looks GREEN!!! cc @nbessi

**Comment by eLBati** [comment]
:+1:

**Comment by nbessi** [comment]
@tafaRU nice, I will make a full review ASAP

**Comment by nbessi** [comment]
Code seems nice :)

It a little hard to review as you probably did not do a git mv so the diff is huge.

But for me it is :+1:.

I will in a next PR  rapatriate code from https://github.com/OCA/l10n-switzerland/pull/63

Thanks

Regards

Nicolas

**Comment by tafaRU** [comment]
> It a little hard to review as you probably did not do a git mv so the diff is huge.

You are right, sorry for this.
On the other hand I'm glad to see you approved our PR!

**Comment by nbessi** [comment]
@tafaRU required dependency is merged, can you rebase, we are almost there :)

**Comment by tafaRU** [comment]
@nbessi NP, which is the branch target on which I have to rebase?

**Comment by guewen** [comment]
@tafaRU The 8.0 one (you will have a conflict at one point)

**Comment by tafaRU** [comment]
@guewen after running `git rebase origin/8.0` I get:

```
First, rewinding head to replay your work on top of it...
Applying: [ADD] Added l10n_ch_base_bank migrated to the new api
Applying: Cleanup of l10n_ch_base_bank port
Applying: Remove old unported code
Applying: Remove deprecated size
Applying: Better variable name
Applying: Renaming variables
Applying: Better function call
Applying: Remove faulty use of _ids
Applying: Typo
Applying: Fix wrong error messages
Applying: Fix forgotten return statement
Applying: Fix exceptions
Applying: Fix exceptions
Applying: Use ValidationError instead of Warning
Applying: [ADD] l10n_ch_dta ported to the new api
Applying: [ADD] 'Agile Bussiness Group' as contributor of porting to v8.0
Applying: [FIX] Delete duplicate and unitil code
Applying: [FIX] W0403(relative-import) pylint error
```

without conflicts. Can I safely now execute `git push -f`?
 Thank you in advance.

**Comment by lepistone** [comment]
FWIW @nbessi @tafaRU `git mv` does the same thing as `git rm` + `git add`. Git tries to find renames after the fact.

@tafaRU your rebase looks correct if you `git fetch origin` before (otherwise your `origin/8.0` is still in an old state).

**Comment by tafaRU** [comment]
@lepistone indeed, you are right, I forgot to fetch :tired_face: 
I made following steps: 
1. git rebase origin/8.0
2. fix the conflicts on the file l10n_ch_base_bank/bank.py and l10n_ch_base_bank/invoice.py
3. git add
4. git rebase --continue

After the last step I get:

```
Applying: Use ValidationError instead of Warning
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

And now, what's next? Can I run `git rebase --skip`?

Thank you in advance.

**Comment by nbessi** [comment]
@tafaRU I think the best you can do at that point is a git rebase --abort and restart sorry.

**Comment by tafaRU** [comment]
@nbessi I tried restarting but the result doesn't change, it's always that described in https://github.com/OCA/l10n-switzerland/pull/57#issuecomment-65103769

I just need to know how can I go on. Thanks.

**Comment by lepistone** [comment]
@tafaRU did you `git add filename.py` ? I think `git add` alone does nothing.

**Comment by tafaRU** [comment]
@lepistone yes sure! I only recapped a bit more, `git add` stands for `git add l10n_ch_base_bank/bank.py l10n_ch_base_bank/invoice.py`

**Comment by tafaRU** [comment]
Just rebased on origin/8.0!

Thanks a lot to @lepistone for his support :grin:

**Pull request merged**
