### PR TITLE
Fix report inherit that changed `report` model to transient

### PR DESCRIPTION
**Pull request by nbessi**

### CODE REVIEW

**Comment by nbessi** [comment]
This should fix runbot

**Comment by guewen** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1: I restarted failing travis job due to `AttributeError: 'module' object has no attribute 'DB'`

**Comment by yvaucher** [comment]
Error was due to an error in `bank_payment`

It was fixed here https://github.com/OCA/bank-payment/commit/1b6728579a2947f3640a7ad57c030d901f6e6068

I restarted the failing job

**Comment by nbessi** [comment]
Green :joy:

**Comment by lepistone** [comment]
:+1:

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by tafaRU** [comment]
:+1:

**Pull request merged**
