### PR TITLE
[11.0][MIG] l10n_ch_scan_bvr

### PR DESCRIPTION
**Pull request by MaxyMoos**
Also contains a small modification to the _l10n_ch_base_bank_ module following [this suggestion](https://github.com/OCA/l10n-switzerland/issues/355#issuecomment-397609781) by @yvaucher

### CODE REVIEW

**Comment by BT-nfrei** [comment]
I did some functional tests on the runbot and it looks good to me.
Can this be merged?
@pedrobaeza and @MaxyMoos , what is your opinion about merging this?

**Comment by BT-nfrei** [comment]
New year, new luck. @pedrobaeza how can we proceed with this PR?

**Comment by pedrobaeza** [comment]
@BT-nfrei on localization repositories, local PSC should drive them. For now, I'm seeing that this PR has conflicting files. You should at least resolve the conflict. Then ping people for reviewing it. Maybe @yvaucher can tell us who is the most suitable.

**Comment by Martronic-SA** [comment]
Despite the fact that this module tries to add all users to a group "l10n_ch_base_bank.group_isr_adherent_num_users" that is not defined anywhere??
After commenting our the security.xml in the __manifest__.py it's working as expected.

**Review by yvaucher — APPROVED** [review]
Oh didn't see your functionnal review @BT-nfrei , don't hesitate to use the review option of github so it is properly notified.

Code LGTM and tests are passing.

Thanks for your work @MaxyMoos (and for the fix of the numerous typos ;) )

**Comment by yvaucher** [comment]
travis errors are not related

**Pull request merged**
