### PR TITLE
[16.0][MIG] l10n_ch_base_bank: Migration to 16.0

### PR DESCRIPTION
**Pull request by BT-anieto**

### CODE REVIEW

**Comment by davidwul** [comment]
@BT-anieto 
May I ask what's the purpose of this module? 
base_bank is not needed anymore for pain_base, credit_transfer and direct_debit. Is this module needed elsewhere?

**Comment by BT-anieto** [comment]
@davidwul Yes, of course! The aim for me was to migrate l10n_ch_pain_credit_transfer. Those are dependencies of the module. If we can remove the dependencies and leave the module as it is, for me it's fine :)

**Comment by davidwul** [comment]
yes, see PR's here, #722 
it's probably just barely ported, but it works without base_bank. 
direct_debit is not ported, but it is in v14 #704 or maybe here if base_bank is not yet removed https://github.com/CompassionCH/l10n-switzerland

**Comment by BT-anieto** [comment]
@davidwul The PR wrong name makes it difficult to follow. You should port module by module with the right commit names (as I did). If you change it, I can review your PRs and close mines

**Comment by BT-anieto** [comment]
Closed because obsolete as stated here #686

**Comment by davidwul** [comment]
Thanks a lot, LGTM
:+1:

**Pull request closed without merging**
