### PR TITLE
12.0

### PR DESCRIPTION
**Pull request by open-net-sarl**
bank and base_bank migration verification and add of dependencies

### CODE REVIEW

**Comment by open-net-sarl** [comment]
Please do not consider the tests.
The commit "bank and base_bank migration verification and add of dependencies" is just setting the manifest " installable: True " and correcting the dependencies.

To pass the checks, .travis.yml has been completed and manifest version modified.

Also, tests have been corrected here:
"
@asaunier pushed 1 commit.

    869f0dd fixup! [MIG] l10n_ch_base_bank: Migration to odoo 12 "


for the migration of fds_postfinance,  the module works like in v11, just corrected the import key from text and hide a useless wizard(the only button he has is not implemented yet)

**Comment by yvaucher** [comment]
@dga-opennet @open-net-sarl please don't forget to look at https://github.com/OCA/l10n-switzerland/issues/445

**Review by yvaucher — CHANGES_REQUESTED** [review]
> bank and base_bank migration verification and add of dependencies

Not sure about the intent of that pull request.
Please give it a proper title and explain why there is also changes in `l10n_ch_fds_postfinance`

By the way, I suggest you to give a proper branch name, named after the feature you want to change.

Here your branch name is 12.0 thus keeping the name allow you to make only one change at a time.

**Comment by yvaucher** [comment]
Migration of l10n_ch_base_bank has already done and l10n_ch_bank migration has been done here:
#479

Closing it.

**Pull request closed without merging**
