### PR TITLE
[11.0][MIG] l10n_ch_fds_postfinance

### PR DESCRIPTION
**Pull request by Nooka10**
I started from PR #444, reactivated the tests and made them work.

### CODE REVIEW

**Comment by yvaucher** [comment]
@Nooka10 thanks for reopening this. As #444 is stalled since April I'll close it.

@ecino Would you mind having a look at it?

**Review by ecino — CHANGES_REQUESTED** [review]
- Some flake8 errors
- You should add a `requirements.txt` file in which you should list `pycrypto` and `pysftp` at the repository root for the python dependencies to install on Travis
- The button icon on the `fds.import.key.wizard` is broken :
image

Otherwise it works as intended :+1:

**Review by ecino — APPROVED** [review]
@yvaucher Now that travis is green, the changes are good for me. I tested the module and everything works well.

**Pull request merged**
