### PR TITLE
[14.0][MIG] l10n_ch_states

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by renzo1974** [comment]
@angelmoya @pedrobaeza What is needed that this PR will be merged?

**Comment by pedrobaeza** [comment]
You should contact contributors from this PSC, as we don't know about the Swish localization

**Comment by yvaucher** [comment]
@rm-jamotion usually it's review that are missing.
I'll merge it anyway as this is a straight forward port.

**Review by angelmoya — APPROVED** [review]
LGTM :+1:

**Comment by angelmoya** [comment]
@rm-jamotion Nice to see you !

You can review code and/or functionality on runbot, then you can add a review, with reviews a manager can merge

**Review by TDu — APPROVED** [review]

**Pull request merged**
