### PR TITLE
[14.0][FIX] l10n_ch_delivery_carrier_label_quickpac: missing condition for …

### PR DESCRIPTION
**Pull request by StephaneMangin**
Missing condition for quickpac when changing carrier on pickings

This PR https://github.com/OCA/l10n-switzerland/pull/637 introduced a bug while using onchange_carrier_id with different carrier than Quickpac.

### CODE REVIEW

**Review by leemannd — APPROVED** [review]
LGTM unless travis failing

**Review by cyrilmanuel — APPROVED** [review]

**Comment by StephaneMangin** [comment]
> LGTM unless travis failing

I don't know why yet, it's working locally

**Comment by TDu** [comment]
@StephaneMangin It needs a rebase to fix the pre-commit. And you can remove this commit https://github.com/OCA/l10n-switzerland/pull/683/commits/93b38befddf7b9e6ad493ae835c5c5352cb4ece5.
And use that opportunity to improve the commit message (see https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message) Thank you.
Otherwise the fix looks good.

**Comment by StephaneMangin** [comment]
@TDu Done !

But now there is a failed test on an independant module `ebill_paynet`.  I'm debugging it.

**Comment by StephaneMangin** [comment]
Waiting for https://github.com/OCA/l10n-switzerland/pull/690 to be reviewed and merged.

**Review by TDu — APPROVED** [review]

**Pull request merged**
