### PR TITLE
WIP: [FIX] Resolves ticket #515 named "Error validating payment XML file" in "bank-payment" repository.

### PR DESCRIPTION
**Pull request by Byloth**
For more extra details, please visit [`bank-payment`'s Issue #515](https://github.com/OCA/bank-payment/issues/515).

---

This PR is also related to...
-  [`bank-payment`'s PR #522](https://github.com/OCA/bank-payment/pull/522)

### CODE REVIEW

**Comment by Byloth** [comment]
As reported by @sbidoul [here](https://github.com/OCA/bank-payment/issues/515#issuecomment-436675418)...
> @Byloth In #522 I provide the hook you need to resolve this properly in l10n-switzerland. So the best way is to override has_fininst_postal_address to return false for the swiss pain flavor.

---
  
Fixing this error requires [`bank-payment`'s PR #522](https://github.com/OCA/bank-payment/pull/522) to be merged.  
Until then, I'll leave this PR open and untouched in order to allow others to temporarily fix the same error with 98d5b323f8fc41ea298370bffb8483ebb9530c02.

**Comment by ecino** [comment]
This is a PR for v10.0 but you wait for a v11.0 PR first? Has the v11 fix to be backported to v10 as well?

**Comment by Byloth** [comment]
> Has the v11 fix to be backported to v10 as well?

Actually, yes... You're right!

**Comment by ecino** [comment]
I think the commit https://github.com/OCA/bank-payment/commit/6bca6c3010d714573f67635d8a22dbd4fe94db77 fixed the issue for v10. We just need to deactivate address in payment method and then it works. We can close this PR in my opinion.

**Comment by yvaucher** [comment]
Thanks. Following comment from @ecino I'm closing this.

**Pull request closed without merging**
