### PR TITLE
[7.0] Fix incorrect due_date for HEAD records in DD files.

### PR DESCRIPTION
**Pull request by ecino**
Head records in Postfinance Direct Debit orders were wrong. The date was incorrectly set.

### CODE REVIEW

**Comment by ecino** [comment]
Travis error is fixed in #81

**Comment by guewen** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by nbessi** [comment]
Fix seems correct but non regression tests are red :hand: until test are green

**Comment by nbessi** [comment]
:+1:

**Pull request merged**
