### PR TITLE
Release 7.3

### PR DESCRIPTION
**Pull request by nbessi**
Change with release 7.3
- Remove compatibility code for BVR/ESR only Multi BVR/ESR is supported
- Add credit control integration with ESR
- Add intergation with account bank reconciliation addons https://launchpad.net/banking-addons/bank-statement-reconcile-7.0 with module  l10n_ch_payment_slip_base_transaction_id
- Uniformize  management of reference

### CODE REVIEW

**Comment by nbessi** [comment]
original MP:
https://code.launchpad.net/~camptocamp/openerp-swiss-localization/payment-slip-evolution-dunning-fees-support-nbi/+merge/218601

To work on OCB depends on lp:~camptocamp/ocb-addons/fix-1308364-nbi
To work on official depends on https://code.launchpad.net/~camptocamp/openobject-addons/7.0-fix-1308364-nbi

Depends on https://code.launchpad.net/~camptocamp/account-financial-tools/add-manual-line-and-fees-nbi/+merge/218584 to support of credit control dunning fees

This PR is an evolution of l10n_ch.

It removes duplicated code used for backward compatibility on BVR/ESR report. Only Multi-BVR/ESR report will remain.

It fixes multi-BVR/ESR report hack due to following bug:
https://bugs.launchpad.net/openobject-addons/+bug/1308364

It refactors and corrects l10n_ch_credit_control_payment_slip_report and add support of fees.

**Comment by nbessi** [comment]
Approved by @yvaucher on LP

**Comment by guewen** [comment]
:warning: do not merge before we switch to github otherwise we may diverge from the launchpad branch

**Comment by nbessi** [comment]
@guewen yes, I will be careful and be sure both branch will not diverge. 
As it is a big PR there probably will be some time before having more review.

**Comment by nbessi** [comment]
Deprecated by https://github.com/OCA/l10n-switzerland/pull/22

**Pull request closed without merging**
